apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - seiberhome.com
    secretName: tls-secret
  rules:
  - host: "seiberhome.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rpi-gd-api-server-service
            port:
              number: 80
