apiVersion: apps/v1
kind: Deployment
metadata:
  name: carport-server-deployment
spec:
  selector:
    matchLabels:
      app: carport-api-server
  template:
    metadata:
      labels:
        app: carport-api-server
    spec:
      containers:
      - name: carport-api-server
        image: iotccrscotts.azurecr.io/carport-service:3.0.7-arm64v8
        ports:
        - containerPort: 9092
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: rpi-gd-acr-access
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rpi-gd-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/rpi-gd/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpi-gd-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: carport-server-service
spec:
  type: LoadBalancer
  selector:
    app: carport-api-server
  ports:
  - name: carport-api-server
    protocol: TCP
    port: 9092
    targetPort: 9092
